name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature. Please describe it clearly so we can evaluate it.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What feature would you like to see added?
      placeholder: A clear description of the feature.
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Why do you need this? What problem does it solve?
      placeholder: As a community admin, I want to... so that...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like to see this implemented? Sketches, mockups, or API designs welcome.
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: How important is this to you?
      options:
        - Nice to have
        - Would significantly improve my workflow
        - Blocking my use of Concord
    validations:
      required: false
